version: "2"
services:
  batch-rekognizer:
    image: turnerlabs/stream
    tty: true
    volumes:
    - /tmp/:/tmp/
    environment:
      STREAM: "${STREAM}"
      NAME: "${NAME}"
      FPS: ${FPS}
